name: Governance Checks

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check-proposals:
    name: Check Uniswap Proposals
    runs-on: ubuntu-latest
    environment: ci
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install required dependencies
        run: |
          apt-get update
          apt-get install -y unzip python3 python3-pip python3-dev build-essential libssl-dev git curl wget

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install solc-select
        run: pip3 install solc-select

      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Install multiple solc versions
        run: |
          solc-select install 0.8.19
          solc-select install 0.8.20
          solc-select use 0.8.20

      - name: Run checks
        run: bun run start
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RPC_URL: ${{ secrets.RPC_URL }}
          TENDERLY_ACCESS_TOKEN: ${{ secrets.TENDERLY_ACCESS_TOKEN }}
          TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
          TENDERLY_PROJECT_SLUG: ${{ secrets.TENDERLY_PROJECT_SLUG }}
          DAO_NAME: 'Uniswap'
          GOVERNOR_ADDRESS: '0x408ED6354d4973f66138C91495F2f2FCbd8724C3'

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Uniswap
          path: reports/Uniswap/0x408ED6354d4973f66138C91495F2f2FCbd8724C3/
