name: Governance Checks

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-proposals:
    name: Check Uniswap Proposals
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install solc-select
        run: pip3 install solc-select

      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Install multiple solc versions
        run: |
          solc-select install 0.8.19
          solc-select install 0.8.20
          solc-select use 0.8.20

      - name: Run checks
        run: yarn start
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RPC_URL: ${{ secrets.RPC_URL }}
          TENDERLY_ACCESS_TOKEN: ${{ secrets.TENDERLY_ACCESS_TOKEN }}
          TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
          TENDERLY_PROJECT_SLUG: ${{ secrets.TENDERLY_PROJECT_SLUG }}
          DAO_NAME: 'Uniswap'
          GOVERNOR_ADDRESS: '0x408ED6354d4973f66138C91495F2f2FCbd8724C3'

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Uniswap
          path: reports/Uniswap/0x408ED6354d4973f66138C91495F2f2FCbd8724C3/
